"""
The `.in` declares, the `.txt` resolves - and every consumer installs the `.txt`.

`requirements.txt` and `requirements-dev.txt` are compiled by `uv pip compile`;
`requirements.in` and `requirements-dev.in` are the hand-edited declarations.
Nothing enforces that at install time, so it is pinned here.

Five separate failures this catches, none of which is visible in review:

1. **A hand-edited lock.** A `>=` or an unhashed line in a `.txt` is someone
   editing the generated file. The next re-compile silently overwrites it, so
   the change disappears without ever failing - the worst shape of bug.
2. **A consumer left on a floating install.** The Dockerfile, `ci.yml` and
   `start.sh` each install independently; one of them dropping `--require-hashes`
   turns `--generate-hashes` back into decoration and lets an unpinned
   transitive float in, while everything stays green.
3. **A rename to `requirements.lock`.** The obvious tidy-up, and the one that
   breaks Dependabot: `pip_compile_file_matcher.rb` only recognises a lockfile
   ending in `.txt` with either an `--output-file <name>` header or a sibling
   `<name>.in`. A `.lock` matches neither, so Dependabot falls back to reading
   the floors and updates the lock never - permanently green automation that
   changes nothing. See AGENTS.md and .github/dependabot.yml.
4. **`pyproject.toml` growing a `[project]` table.** It exists to configure
   ruff, mypy and coverage and nothing else. `conftest.py` at the backend root
   is what puts that directory on `sys.path`, so a test's `import app.main`
   resolves to the file `uvicorn app.main:app` loads and `COPY app/ ./app/`
   ships. Declaring a project makes `pip install -e .` possible, and the first
   person to run it gets a second importable copy through site-packages: two
   `Violation` classes, and a suite passing against a layout the container does
   not have. It would also move the dev tools out of the lock, out of
   `--require-hashes`, out of CI's drift check and out of Dependabot at once.
5. **A `pytest.ini` coming back.** The pytest configuration moved into
   `pyproject.toml`, and the two cannot coexist: `pytest.ini` outranks
   `pyproject.toml` and wins *silently* - no conflict, no warning. The
   `[tool.pytest.ini_options]` section would simply stop being read while the
   suite kept passing under different settings, which is the same shape as a
   hand-edited lock.

There is deliberately no assertion on *which versions* the locks pin. That is
what the eval and the test suite measure, and pinning it twice would mean every
dependency bump edits this file.
"""

import re
from pathlib import Path

import pytest

BACKEND_DIR = Path(__file__).resolve().parents[1]
REPO_ROOT = BACKEND_DIR.parent

LOCKS = ("requirements.txt", "requirements-dev.txt")
DECLARATIONS = ("requirements.in", "requirements-dev.in")

# uv's own header, which doubles as the regeneration instructions. Matching it
# loosely on purpose: the exact flags are CONTRIBUTING.md's business and the CI
# drift check's, and duplicating them here would make this test the third place
# a flag change has to land.
UV_HEADER = "autogenerated by uv"

# Tables that turn a configuration file into a package manifest. `project` and
# `build-system` are the obvious two. `dependency-groups` (PEP 735) is the one
# somebody reaches for later, because it looks like the modern place to declare
# dev tools - and it sits outside the lock, the drift check and Dependabot all
# at once.
PACKAGE_MANIFEST_TABLES = ("project", "build-system", "dependency-groups")

# pytest reads the first of these it finds and stops. Every one outranks
# pyproject.toml.
COMPETING_PYTEST_CONFIGS = ("pytest.ini", ".pytest.ini", "setup.cfg", "tox.ini")

# The tools the backend gate runs. Declared in requirements-dev.in so they are
# pinned by the lock like everything else.
DEV_TOOLS = ("ruff", "mypy", "pytest-cov")


def _requirement_lines(path):
    """Non-comment, non-continuation requirement lines from a compiled lock."""
    lines = []
    for raw in path.read_text().splitlines():
        stripped = raw.strip()
        if not stripped or stripped.startswith("#"):
            continue
        # Hash continuations are indented; a requirement starts at column 0.
        if raw[:1].isspace():
            continue
        lines.append(stripped)
    return lines


@pytest.mark.parametrize("name", DECLARATIONS)
def test_declaration_exists(name):
    assert (BACKEND_DIR / name).is_file(), (
        f"backend/{name} is the hand-edited declaration and must exist; "
        "the .txt next to it is generated from it."
    )


@pytest.mark.parametrize("name", LOCKS)
def test_lock_is_generated_and_says_so(name):
    """
    The header is the only thing telling a reader the file is generated - a
    banner cannot be prepended, because uv rewrites the header on every compile
    and `--custom-compile-command` is single-line only (a newline in it emits an
    uncommented line and corrupts the file).
    """
    header = (BACKEND_DIR / name).read_text().splitlines()[0]
    assert UV_HEADER in header, (
        f"backend/{name} has lost its generated-file header. It is compiled by "
        "`uv pip compile`, not hand-written - see CONTRIBUTING.md."
    )


@pytest.mark.parametrize("name", LOCKS)
def test_lock_is_fully_pinned_and_hashed(name):
    """
    Every requirement is `==` and carries at least one hash. A `>=` means
    someone pasted a declaration into the lock; a missing hash means
    `--require-hashes` would refuse the whole file at install time, which is a
    red build rather than a silent one - but only for whoever installs first.
    """
    text = (BACKEND_DIR / name).read_text()
    for line in _requirement_lines(BACKEND_DIR / name):
        # Universal resolution appends an environment marker, which legitimately
        # contains `>=` (`numpy==2.4.6 ; python_full_version >= '3.11'`). Only
        # the requirement half is a version specifier.
        spec = line.split(";")[0].strip()
        assert "==" in spec, (
            f"backend/{name} line {line!r} is not pinned. This file is "
            "generated - add the floor to the .in and re-compile."
        )
        assert ">=" not in spec, f"backend/{name} carries a floor: {line!r}"
        # `pkg==1.2.3 \` opens the hash block that follows it.
        assert line.rstrip().endswith("\\"), (
            f"backend/{name} line {line!r} has no hash block. Re-compile with "
            "--generate-hashes; without it --require-hashes fails the install."
        )
    assert "--hash=sha256:" in text


def test_dev_lock_is_a_superset_of_the_runtime_lock():
    """
    `requirements-dev.in` starts `-r requirements.in`, so the dev lock must
    contain everything the runtime lock does. Re-compiling only one of the two
    is the mistake this catches: CI installs the dev lock and would keep
    passing while the image installed something else.
    """
    dev_in = (BACKEND_DIR / "requirements-dev.in").read_text()
    assert "-r requirements.in" in dev_in, (
        "requirements-dev.in must include requirements.in, or the dev lock "
        "stops describing what the app actually runs on."
    )

    def pins(name):
        return {line.split("==")[0] for line in _requirement_lines(BACKEND_DIR / name)}

    missing = pins("requirements.txt") - pins("requirements-dev.txt")
    assert not missing, (
        f"requirements-dev.txt is missing {sorted(missing)}. The two locks were "
        "compiled at different times - re-compile both, in the same commit."
    )


def test_no_second_requirements_file_inside_the_package():
    """
    `app/analysis/requirements.txt` used to exist: unreferenced, contradicting
    the real declaration, and shipped into the image by `COPY app/ ./app/`. Now
    that `requirements.txt` means "the lock", a second unlocked one inside the
    package is the file someone eventually installs by accident.
    """
    strays = [
        p.relative_to(REPO_ROOT)
        for p in (BACKEND_DIR / "app").rglob("requirements*.txt")
    ]
    assert not strays, f"requirements files inside the package: {strays}"


def test_dockerfile_installs_the_lock_with_hashes():
    dockerfile = (BACKEND_DIR / "Dockerfile").read_text()
    assert "--require-hashes -r requirements.txt" in dockerfile, (
        "backend/Dockerfile must install the lock with --require-hashes; "
        "without it the compiled hashes are decoration."
    )
    # Comments stripped first - the pip layer's comment explains why the .in is
    # absent, and naming it there is not COPYing it.
    instructions = "\n".join(
        line for line in dockerfile.splitlines() if not line.lstrip().startswith("#")
    )
    assert "requirements.in" not in instructions, (
        "The image installs the resolution, never the declaration."
    )


def test_every_consumer_installs_with_require_hashes():
    """
    Five places install these files independently. One of them drifting back
    to a bare `pip install -r` is invisible: it still resolves, still boots,
    and quietly stops being the build the other two produce.

    Comment lines are skipped, the same way `test_dockerfile_installs_the_lock`
    strips them: every one of these files explains itself in prose, and a
    comment that *names* an install command is not running one. The
    devcontainer's post-create script and the Makefile joined the list in
    Phase C; both exist to make "running what CI runs" one command shorter,
    which is worthless if the command they run is a different build. ci.yml's ruff
    steps say why they do not use astral-sh/ruff-action - because it would
    install a ruff other than the one `pip install -r requirements-dev.txt`
    does - and quoting the command there is the clearest way to say it.
    """
    consumers = {
        "start.sh": REPO_ROOT / "start.sh",
        "ci.yml": REPO_ROOT / ".github" / "workflows" / "ci.yml",
        "Dockerfile": BACKEND_DIR / "Dockerfile",
        "post-create.sh": REPO_ROOT / ".devcontainer" / "post-create.sh",
        "Makefile": REPO_ROOT / "Makefile",
    }
    bare_install = re.compile(
        r"pip install\s+(?![^\n]*--require-hashes)[^\n]*-r\s+requirements"
    )
    for label, path in consumers.items():
        offenders = [
            line.strip()
            for line in path.read_text().splitlines()
            if not line.lstrip().startswith("#") and bare_install.search(line)
        ]
        assert not offenders, (
            f"{label} installs a requirements file without --require-hashes: {offenders}"
        )


def test_pyproject_is_configuration_only():
    """
    `backend/pyproject.toml` configures tools; it must never declare a package.

    Failure 4 in this module's docstring. Asserted textually rather than with
    `tomllib`, which is 3.11+ while the locks compile for 3.10 - adding a TOML
    parser to the lock for one test is a worse trade than a regex.
    """
    text = (BACKEND_DIR / "pyproject.toml").read_text()
    tables = re.findall(r"^\[+([^\]]+)\]+", text, flags=re.MULTILINE)

    offenders = [t for t in tables if t.split(".")[0] in PACKAGE_MANIFEST_TABLES]
    assert not offenders, (
        f"backend/pyproject.toml declares {offenders}. It is tool configuration "
        "only - see its header, and conftest.py's docstring for why the backend "
        "must not become an installed package."
    )
    assert tables, "backend/pyproject.toml has no [tool.*] tables at all."
    assert all(t.startswith("tool.") for t in tables), (
        f"unexpected top-level tables in backend/pyproject.toml: {tables}"
    )


def test_pytest_is_configured_in_exactly_one_place():
    """
    Failure 5: a re-added `pytest.ini` would not conflict and would not warn.
    It would silently outrank `[tool.pytest.ini_options]`, and the suite would
    keep passing under settings nobody chose.
    """
    strays = [n for n in COMPETING_PYTEST_CONFIGS if (BACKEND_DIR / n).is_file()]
    assert not strays, (
        f"{strays} would silently override [tool.pytest.ini_options]. "
        "backend/pyproject.toml is the only pytest configuration."
    )
    assert "[tool.pytest.ini_options]" in (BACKEND_DIR / "pyproject.toml").read_text()


@pytest.mark.parametrize("tool", DEV_TOOLS)
def test_dev_tools_are_declared_in_the_lock_not_in_pyproject(tool):
    """
    The tools that police the build must not be the one thing in it still
    floating. Declared in requirements-dev.in, they are pinned by the compiled
    lock, installed with --require-hashes, re-checked by CI's drift step and
    watched by Dependabot - the same machinery as every runtime dependency.
    """
    assert tool in (BACKEND_DIR / "requirements-dev.in").read_text(), (
        f"{tool} must be declared in requirements-dev.in, not in pyproject.toml"
    )


def test_ci_caches_on_the_lock_not_the_declaration():
    """
    `cache-dependency-path` keyed on a `.in` would reuse a cache across a
    re-compile that changed every version in the lock.
    """
    ci = (REPO_ROOT / ".github" / "workflows" / "ci.yml").read_text()
    assert "cache-dependency-path: backend/requirements-dev.txt" in ci
